import { Card, CardContent } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="py-8">
      <div className="container max-w-4xl">
        <h1 className="font-serif text-3xl font-bold mb-2" data-testid="text-page-title">
          Terms of Service
        </h1>
        <p className="text-muted-foreground mb-8">Last updated: January 2026</p>

        <div className="space-y-8">
          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing and using AI Blueprint Pulse ("the Platform"), you agree to be bound by 
                these Terms of Service. If you do not agree to these terms, please do not use our services.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>2. Description of Services</h2>
              <p>
                AI Blueprint Pulse provides AI-synthesized business guides ("Success Blueprints") created 
                using proprietary research tools and trend-analysis algorithms. Our services include 
                the Blueprint Marketplace, Research Engine, and downloadable business guides.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>3. License & Usage Rights</h2>
              <ul>
                <li>
                  <strong>Personal/Internal Use Only:</strong> Purchase of any guide grants you a 
                  non-exclusive, non-transferable license to use this information for your own 
                  business or internal company growth.
                </li>
                <li>
                  <strong>No Resale:</strong> You may not repackage, white-label, or resell the 
                  contents of any blueprint as your own consulting or educational product without 
                  an Enterprise-tier partnership agreement.
                </li>
                <li>
                  <strong>AI Disclosure:</strong> Guides are synthesized using the AI Blueprint Pulse 
                  Research Engine. While we strive for accuracy, business trends shift rapidly; 
                  content is for strategic guidance and does not guarantee specific financial results.
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>4. Intellectual Property & Ownership</h2>
              <p>
                All "Success Blueprints," research reports, and strategic frameworks generated by 
                the AI Blueprint Pulse platform are the property of the Company. The User acknowledges 
                that the value of the Services lies in the proprietary "Back-End" research tools, 
                trend-analysis algorithms, and curated prompts developed by the Company.
              </p>
              <p>
                While the User is granted a license to implement the strategies contained within a 
                purchased Blueprint, the arrangement, selection, and coordination of the data—even 
                where AI-assisted—constitutes a copyrighted work under current intellectual property 
                statutes. Users may not "scrape" the platform or use automated tools to extract the 
                underlying research logic for the purpose of creating a competing service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>5. AI-Generated Content Disclosure</h2>
              <p>
                AI Blueprint Pulse utilizes artificial intelligence, including but not limited to 
                OpenAI's GPT models and Tavily web search, to synthesize market research and 
                generate business guidance. All content is:
              </p>
              <ul>
                <li>Generated using AI-assisted analysis</li>
                <li>Based on real-time web research and trend data</li>
                <li>Reviewed through proprietary quality frameworks</li>
                <li>Provided "as-is" without guarantee of specific outcomes</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>6. Market Dynamics Notice</h2>
              <p>
                Blueprints are snapshots of digital trends at a specific point in time. Success in 
                online business depends on execution, market volatility, and external factors beyond 
                the scope of this research tool. AI Blueprint Pulse provides "Blueprints," not "Guarantees."
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>7. Digital Product & Refund Policy</h2>
              
              <h3>7.1 All Sales Final</h3>
              <p>
                Due to the immediate access and intangible nature of digital "Success Blueprints," 
                all sales are generally final. Unlike physical goods, digital data cannot be "returned" 
                once it has been downloaded or viewed. By completing your purchase, you acknowledge 
                that you are gaining instant access to proprietary research and AI-synthesized 
                intellectual property.
              </p>

              <h3>7.2 Quality Signal Guarantee</h3>
              <p>
                We stand by the caliber of our Research Engine. If you believe a purchased Blueprint 
                is technically defective or fundamentally fails to address the specific niche and 
                level selected at checkout, we offer a 48-hour correction window:
              </p>
              <ul>
                <li>
                  <strong>Correction:</strong> We will re-run the research query using updated 
                  parameters to provide a more accurate guide at no additional cost.
                </li>
                <li>
                  <strong>Credit:</strong> If a correction does not solve the issue, we may, 
                  at our sole discretion, issue a "Blueprint Credit" for use on a future guide.
                </li>
              </ul>

              <h3>7.3 Exclusions from Refunds</h3>
              <p>Refunds or credits will not be issued for the following reasons:</p>
              <ul>
                <li>
                  <strong>"Change of Mind":</strong> Deciding the business model isn't right for 
                  you after viewing the roadmap.
                </li>
                <li>
                  <strong>"Already Knew This":</strong> As these guides are synthesized from 
                  real-time market data, they may reflect common industry trends you are already 
                  aware of.
                </li>
                <li>
                  <strong>Financial Performance:</strong> We provide the blueprint; we do not 
                  provide the execution. Lack of business success or profit is not grounds for 
                  a refund.
                </li>
              </ul>

              <h3>7.4 Abuse Prevention</h3>
              <p>
                To protect the integrity of the platform, accounts that exhibit a pattern of 
                multiple refund requests or "credit" claims will be flagged. AI Blueprint Pulse 
                reserves the right to terminate access for users who attempt to "scrape" data 
                via the refund process.
              </p>

              <h3>7.5 How to Initiate a Review</h3>
              <p>
                To request a guide correction or credit, please contact support within 48 hours 
                of purchase with your Order ID and a specific description of the data gap or 
                technical error in the guide.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>8. Limitation of Liability</h2>
              <p>
                AI Blueprint Pulse and its affiliates shall not be liable for any indirect, incidental, 
                special, consequential, or punitive damages resulting from your use of or inability 
                to use the service, including but not limited to loss of profits, data, or business 
                opportunities.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>9. Contact Information</h2>
              <p>
                For questions about these Terms of Service, please contact us through the Platform.
              </p>
            </CardContent>
          </Card>

          <div className="text-center text-sm text-muted-foreground pt-4">
            © 2026 AI Blueprint Pulse. All Rights Reserved.
          </div>
        </div>
      </div>
    </div>
  );
}
