import { Card, CardContent } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="py-8">
      <div className="container max-w-4xl">
        <h1 className="font-serif text-3xl font-bold mb-2" data-testid="text-page-title">
          Terms of Service
        </h1>
        <p className="text-muted-foreground mb-8">Last updated: January 2026</p>

        <div className="space-y-8">
          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing and using Blueprint Nexus ("the Platform"), you agree to be bound by 
                these Terms of Service. If you do not agree to these terms, please do not use our services.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>2. Description of Services</h2>
              <p>
                Blueprint Nexus provides AI-synthesized business guides ("Success Blueprints") created 
                using proprietary research tools and trend-analysis algorithms. Our services include 
                the Blueprint Marketplace, Research Engine, and downloadable business guides.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>3. License & Usage Rights</h2>
              <ul>
                <li>
                  <strong>Personal/Internal Use Only:</strong> Purchase of any guide grants you a 
                  non-exclusive, non-transferable license to use this information for your own 
                  business or internal company growth.
                </li>
                <li>
                  <strong>No Resale:</strong> You may not repackage, white-label, or resell the 
                  contents of any blueprint as your own consulting or educational product without 
                  an Enterprise-tier partnership agreement.
                </li>
                <li>
                  <strong>AI Disclosure:</strong> Guides are synthesized using the Blueprint Nexus 
                  Research Engine. While we strive for accuracy, business trends shift rapidly; 
                  content is for strategic guidance and does not guarantee specific financial results.
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>4. Intellectual Property & Ownership</h2>
              <p>
                All "Success Blueprints," research reports, and strategic frameworks generated by 
                the Blueprint Nexus platform are the property of the Company. The User acknowledges 
                that the value of the Services lies in the proprietary "Back-End" research tools, 
                trend-analysis algorithms, and curated prompts developed by the Company.
              </p>
              <p>
                While the User is granted a license to implement the strategies contained within a 
                purchased Blueprint, the arrangement, selection, and coordination of the data—even 
                where AI-assisted—constitutes a copyrighted work under current intellectual property 
                statutes. Users may not "scrape" the platform or use automated tools to extract the 
                underlying research logic for the purpose of creating a competing service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>5. AI-Generated Content Disclosure</h2>
              <p>
                Blueprint Nexus utilizes artificial intelligence, including but not limited to 
                OpenAI's GPT models and Tavily web search, to synthesize market research and 
                generate business guidance. All content is:
              </p>
              <ul>
                <li>Generated using AI-assisted analysis</li>
                <li>Based on real-time web research and trend data</li>
                <li>Reviewed through proprietary quality frameworks</li>
                <li>Provided "as-is" without guarantee of specific outcomes</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>6. Market Dynamics Notice</h2>
              <p>
                Blueprints are snapshots of digital trends at a specific point in time. Success in 
                online business depends on execution, market volatility, and external factors beyond 
                the scope of this research tool. Blueprint Nexus provides "Blueprints," not "Guarantees."
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>7. Refund Policy</h2>
              <p>
                We offer a 30-day money-back guarantee on all Blueprint purchases. If you are 
                unsatisfied with your purchase for any reason, contact our support team within 
                30 days of purchase for a full refund.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>8. Limitation of Liability</h2>
              <p>
                Blueprint Nexus and its affiliates shall not be liable for any indirect, incidental, 
                special, consequential, or punitive damages resulting from your use of or inability 
                to use the service, including but not limited to loss of profits, data, or business 
                opportunities.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6 prose prose-sm dark:prose-invert max-w-none">
              <h2>9. Contact Information</h2>
              <p>
                For questions about these Terms of Service, please contact us through the Platform.
              </p>
            </CardContent>
          </Card>

          <div className="text-center text-sm text-muted-foreground pt-4">
            © 2026 Blueprint Nexus. All Rights Reserved.
          </div>
        </div>
      </div>
    </div>
  );
}
